import React from 'react';
import { Download, Globe, Smartphone, CheckCircle, ExternalLink, Zap } from 'lucide-react';

export const HostingGuideModal = () => {
  return (
    <div className="max-w-2xl mx-auto space-y-6 pb-16">
      {/* Header */}
      <div className="text-center space-y-2">
        <div className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full bg-emerald-500/20 text-emerald-300 text-xs font-bold border border-emerald-500/30">
          <Download className="w-3.5 h-3.5" />
          <span>Mobile Install & Free Hosting</span>
        </div>
        <h2 className="text-2xl font-bold text-white">How to Install on Phone & Host Freely</h2>
        <p className="text-xs text-slate-400">
          Get this app running on your mobile device for offline use in Nepal!
        </p>
      </div>

      {/* 1. Install as PWA App on Phone */}
      <div className="glass-card p-6 rounded-3xl border border-white/10 space-y-4 shadow-xl">
        <h3 className="text-lg font-bold text-amber-300 flex items-center gap-2">
          <Smartphone className="w-5 h-5 text-amber-400" />
          <span>1. Install directly to your Phone Home Screen (Offline PWA)</span>
        </h3>
        <p className="text-xs text-slate-300 leading-relaxed">
          Because this app is built as a Progressive Web App (PWA), you can download and use it like a native app on your phone without needing Google Play Store or Apple App Store!
        </p>

        <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 text-xs">
          <div className="bg-slate-900/80 p-4 rounded-2xl border border-white/5 space-y-2">
            <span className="font-bold text-amber-400">🤖 Android (Chrome Browser):</span>
            <ol className="list-decimal list-inside space-y-1.5 text-slate-300">
              <li>Open this website link in Chrome on your Android phone.</li>
              <li>Tap the <strong>3 dots (Menu)</strong> at top right.</li>
              <li>Tap <strong>"Add to Home screen"</strong> or <strong>"Install app"</strong>.</li>
              <li>Launch anytime from your app drawer offline!</li>
            </ol>
          </div>

          <div className="bg-slate-900/80 p-4 rounded-2xl border border-white/5 space-y-2">
            <span className="font-bold text-amber-400">🍏 iPhone (Safari Browser):</span>
            <ol className="list-decimal list-inside space-y-1.5 text-slate-300">
              <li>Open this website link in Safari on your iPhone.</li>
              <li>Tap the <strong>Share icon</strong> (square with up arrow).</li>
              <li>Scroll down and tap <strong>"Add to Home Screen"</strong>.</li>
              <li>The MeroNepali icon will appear on your iPhone screen!</li>
            </ol>
          </div>
        </div>
      </div>

      {/* 2. Free Hosting Options */}
      <div className="glass-card p-6 rounded-3xl border border-white/10 space-y-4 shadow-xl">
        <h3 className="text-lg font-bold text-teal-300 flex items-center gap-2">
          <Globe className="w-5 h-5 text-teal-400" />
          <span>2. Host Freely on the Internet (0$ Cost)</span>
        </h3>
        <p className="text-xs text-slate-300 leading-relaxed">
          You can host this application permanently online for free using any of these top platforms:
        </p>

        <div className="space-y-3 text-xs">
          <div className="bg-slate-900/80 p-4 rounded-2xl border border-white/5 space-y-2">
            <div className="flex items-center justify-between">
              <span className="font-bold text-white text-sm">Option A: Vercel (Recommended - 1 Click)</span>
              <span className="px-2 py-0.5 rounded bg-emerald-500/20 text-emerald-300 font-mono text-[10px]">Free Tier</span>
            </div>
            <p className="text-slate-300">
              Run <code className="bg-slate-800 px-1.5 py-0.5 rounded text-amber-300">npx vercel</code> in terminal, or connect your GitHub repository directly to Vercel.com. It auto-detects Vite and deploys in 20 seconds.
            </p>
          </div>

          <div className="bg-slate-900/80 p-4 rounded-2xl border border-white/5 space-y-2">
            <div className="flex items-center justify-between">
              <span className="font-bold text-white text-sm">Option B: Netlify</span>
              <span className="px-2 py-0.5 rounded bg-emerald-500/20 text-emerald-300 font-mono text-[10px]">Free Tier</span>
            </div>
            <p className="text-slate-300">
              Drag & drop your <code className="bg-slate-800 px-1.5 py-0.5 rounded text-amber-300">dist</code> folder (generated by <code className="bg-slate-800 px-1.5 py-0.5 rounded text-amber-300">npm run build</code>) onto netlify.com/drop.
            </p>
          </div>

          <div className="bg-slate-900/80 p-4 rounded-2xl border border-white/5 space-y-2">
            <div className="flex items-center justify-between">
              <span className="font-bold text-white text-sm">Option C: Local Network Access (Wi-Fi)</span>
              <span className="px-2 py-0.5 rounded bg-blue-500/20 text-blue-300 font-mono text-[10px]">Immediate</span>
            </div>
            <p className="text-slate-300">
              Run <code className="bg-slate-800 px-1.5 py-0.5 rounded text-amber-300">npm run dev -- --host</code> in your computer terminal. Open the displayed network IP address on your phone connected to the same Wi-Fi network!
            </p>
          </div>
        </div>
      </div>
    </div>
  );
};
